In [1]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)


In [2]:
a


array([[-0.6478618 ,  0.40372248,  0.3588264 ],
       [ 0.03081998,  1.30185551,  1.29215809],
       [-0.50172504, -0.18774471,  2.39954282]])

In [3]:
b

array([[ 0.4334645 ],
       [ 0.1847019 ],
       [-0.19688493]])

In [4]:
c = (a * b).shape

In [5]:
c

(3, 3)

In [6]:
a * b

array([[-0.28082509,  0.17499936,  0.15553851],
       [ 0.00569251,  0.24045518,  0.23866405],
       [ 0.0987821 ,  0.0369641 , -0.47243381]])

In [7]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 